// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePoint = "points"

// Point mapped from table <points>
type Point struct {
	ID        string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	UserID    *string    `gorm:"column:user_id;type:text" json:"user_id"`
	Balance   int32      `gorm:"column:balance;type:integer;not null" json:"balance"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Point's table name
func (*Point) TableName() string {
	return TableNamePoint
}
