// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "tasks"

// Task mapped from table <tasks>
type Task struct {
	ID           string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	Name         string     `gorm:"column:name;type:text;not null" json:"name"`
	Description  *string    `gorm:"column:description;type:text" json:"description"`
	PointsReward int32      `gorm:"column:points_reward;type:integer;not null" json:"points_reward"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
