// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID           string     `gorm:"column:id;type:text;primaryKey" json:"id"`
	Username     string     `gorm:"column:username;type:text;not null" json:"username"`
	Email        string     `gorm:"column:email;type:text;not null" json:"email"`
	PasswordHash string     `gorm:"column:password_hash;type:text;not null" json:"password_hash"`
	CreatedAt    *time.Time `gorm:"column:created_at;type:datetime;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
