run:
  timeout: 5m

linters:
  enable:
    - errcheck # Проверяет, что ошибки не игнорируются
    - gosimple # Упрощает код, убирая избыточные конструкции
    - govet # Анализирует код и выявляет потенциальные ошибки
    - ineffassign # Находит неиспользуемые присваивания
    - staticcheck # Глубокий статический анализ кода
    - unused # Ищет неиспользуемые переменные, функции, типы и т. д.
    - gosec # Анализ безопасности кода
    - revive # Улучшенная версия golint с возможностью гибкой настройки
    - gocyclo # Анализирует сложность функций
    - unconvert # Находит ненужные приведения типов
    - prealloc # Оптимизирует выделение памяти в слайсах

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
